# Generated by Django 5.2.7 on 2025-10-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JDRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("input_json", models.JSONField()),
                ("word_count", models.IntegerField(blank=True, null=True)),
                ("tone", models.CharField(blank=True, default="", max_length=64)),
                (
                    "language",
                    models.CharField(blank=True, default="English", max_length=32),
                ),
                ("output_text", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("error", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
